name: CD

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: docker build -t ghcr.io/${{ github.repository }}:${{ github.sha }} .
        # Use a unique tag based on the commit SHA to easily reference specific builds

      - name: Log into GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }} 
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker Image
        run: docker push ghcr.io/${{ github.repository }}:${{ github.sha }}

      # Optional: Push a 'latest' tag for convenience
      - name: Push Latest Tag
        run: |
          docker tag ghcr.io/${{ github.repository }}:${{ github.sha }} ghcr.io/${{ github.repository }}:latest
          docker push ghcr.io/${{ github.repository }}:latest
